services:
  db:
    image: mysql:8.0
    container_name: Board-MYSQL
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - Board-Net

  backend:
    container_name: Board-Backend
    build:
      context: ../board-backend
    volumes:
      - static_volume:/Backend/static
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - Board-Net
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn --bind 0.0.0.0:8000 config.wsgi:application --timeout 300"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"  # 백틱으로 수정
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    privileged: true

  traefik:
    image: traefik:v2.10
    container_name: Board-Traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"       # 사용자 요청 처리
      - "8080:8080"   # 대시보드 확인용
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Board-Net

volumes:
  db_data:
  static_volume:

networks:
  Board-Net:
    driver: bridge