global:
  scrape_interval: 15s  # 메트릭 수집 인터벌
  evaluation_interval: 15s  # 메트릭 평가 인터벌

scrape_configs:
  - job_name: 'prometheus-data'  # Prometheus 자체 메트릭 수집
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'board-backend'  # Django (Board-Backend) 메트릭 수집
    static_configs:
      - targets: ['backend:8000']
